development:
  adapter: postgresql
  database: froks_weather_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: froks_weather_bot_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: froks_weather_bot_production
  pool: 5
  timeout: 5000